### ISSUE TITLE
MakeJSONRequest GET with Body

### ISSUE THREAD

**Issue by scottix** [zenoverflow/omnichain#1]
Issue: When using GET or HEAD method it doesn't require a body.

1. Create a MakeJSONRequest object use GET as the method
2. Get this error `{"code":0,"data":null,"error":"Request with GET/HEAD method cannot have body."}`

Details:
https://github.com/zenoverflow/omnichain/blob/e166b4702ba5c72408e9a9b090416a007016810e/src/nodes/_nodes/MakeJSONRequestNode.ts#L80

**Comment by zenoverflow** [comment]
The node was originally made for requests to backends that don't yet have native nodes, so it was always tested with POST and a body. I'll tweak it to support not having a body.

**Comment by zenoverflow** [comment]
#9f96800 modifies the code so the body is optional and the response doesn't have to be valid json (to support text/plain).

**Comment by zenoverflow** [comment]
Done testing, so I'm closing this for now.
