### ISSUE TITLE
OpenAIChatCompletion result is not connecting to GrabText node

### ISSUE THREAD

**Issue by Israel-Laguan** [zenoverflow/omnichain#8]
I opened the "Example - NodeJS Agent" and tried to change default "OllamaChatCompletion" to use openai one instead, but when I was able to connect "system message" and "message (array)" the result one is not working. 

I then changed to "LMStudioChatCompletion" which worked flawlessly.

[omnichain-openaichatcompletion.webm](https://github.com/user-attachments/assets/b41d728d-a193-4bf3-9ac1-40e3193a675f)

I also tried to use an intermediate node but without luck.

No errors on browser or in the console.

**Comment by zenoverflow** [comment]
Of course it doesn't. The OpenAI nodes output arrays. That connection requires a single string.

**Comment by Israel-Laguan** [comment]
Ah got it. With that I was able to connect

![image](https://github.com/user-attachments/assets/91de900f-5332-41ec-9496-bf5fd267b95a)

Maybe would be good to change the text in the UI to "result (array)" or similar?

Thanks for the help!

**Comment by Israel-Laguan** [comment]
Closign the issue as it was resolved, thanks @zenoverflow !
