### ISSUE TITLE
[Bug] Ollama completion nodes Top-K parameter has wrong limits

### ISSUE THREAD

**Issue by DatCaptainHorse** [zenoverflow/omnichain#9]
### Issue

As with title, Ollama completion nodes (Chat and Text completion) have top_k value parameter which can't go above 1, it seems to be using top_p's limits.

**Comment by zenoverflow** [comment]
Looked through all nodes that use top_k and changed min value to 0 while removing the max limit. You can update to the latest version (0.1.8) to get the fix and confirm it's fine on your side.

**Comment by DatCaptainHorse** [comment]
Works immediately, thanks for quick fix :+1:
